import { Geist, Geist_Mono } from "next/font/google";
import "@/app/shared/styles/globals.css";
import "@/app/shared/styles/colors.css";

import Navbar from "@/app/presentation/components/NavBar";
import Footer from "@/app/presentation/components/Footer";
import Aside from "@/app/presentation/components/Aside";
import { AuthProvider } from "@/app/presentation/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen branding-gradient">
        <AuthProvider>
          <Navbar />
          <div className="flex flex-grow container p-6">
            <Aside />
            <main className="flex-grow">{children}</main>
          </div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
